name: Question ❓
description: Ask a question about the project
title: "[Question] "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for asking a question! We're here to help.

  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
      placeholder: Ask your question here...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What type of question is this?
      options:
        - How to use xccache-agent
        - Configuration help
        - Troubleshooting
        - Best practices
        - Integration with other tools
        - Performance optimization
        - Other
    validations:
      required: true
